# permissions for end users to view objstores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cninf
    app.kubernetes.io/managed-by: kustomize
  name: objstore-viewer-role
rules:
- apiGroups:
  - cninf.operators.praneel.com
  resources:
  - objstores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cninf.operators.praneel.com
  resources:
  - objstores/status
  verbs:
  - get
